-- 001_init_users_tokens
CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(512) NOT NULL,
    base_folder VARCHAR(255) UNIQUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS user_tokens (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    token VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT fk_user_id FOREIGN KEY (user_id) REFERENCES users(id)
);

-- Format of user basic folder
CREATE OR REPLACE FUNCTION init_user_folder_func()
RETURNS TRIGGER AS $$
    BEGIN
        NEW.base_folder := NEW.id || '_' || NEW.email || ':';
        RETURN NEW;
    END;
$$ LANGUAGE plpgsql;

-- Init base folder in db
CREATE OR REPLACE TRIGGER init_user_folder
    BEFORE INSERT ON users
    FOR EACH ROW
    EXECUTE FUNCTION init_user_folder_func();