-- 002_file_storage
CREATE TABLE IF NOT EXISTS dirs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(1024) NOT NULL,
    parent_id BIGINT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT dir_parent_id FOREIGN KEY (parent_id) REFERENCES dirs(id) ON DELETE CASCADE,
    UNIQUE (name, parent_id)
);

CREATE TABLE IF NOT EXISTS user_dirs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    dir_id BIGINT NOT NULL,
    role VARCHAR(50) DEFAULT 'OWNER' NOT NULL,
    CONSTRAINT ud_user_id FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT ud_dir_id FOREIGN KEY (dir_id) REFERENCES dirs(id) ON DELETE CASCADE,
    UNIQUE (user_id, dir_id)
);

CREATE TABLE IF NOT EXISTS files (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(1024) NOT NULL,
    size BIGINT NOT NULL DEFAULT 0,
    mime_type VARCHAR(255),
    storage_key VARCHAR(1024),
    hash VARCHAR(64),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS dir_files (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_dir_id BIGINT NOT NULL,
    file_id BIGINT NOT NULL,
    CONSTRAINT udf_user_dir_id FOREIGN KEY (user_dir_id) REFERENCES dirs(id) ON DELETE CASCADE,
    CONSTRAINT udf_file_id FOREIGN KEY (file_id) REFERENCES files(id) ON DELETE CASCADE,
    UNIQUE (user_dir_id, file_id)
);

CREATE TABLE IF NOT EXISTS tags (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS file_tags (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    file_id BIGINT NOT NULL,
    tag_id BIGINT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT ft_file_id FOREIGN KEY (file_id) REFERENCES files(id) ON DELETE CASCADE,
    CONSTRAINT ft_tag_id FOREIGN KEY (tag_id) REFERENCES tags(id) ON DELETE CASCADE,
    UNIQUE (file_id, tag_id)
);

CREATE TABLE IF NOT EXISTS shares (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    resource_type VARCHAR(50) NOT NULL CHECK (resource_type IN ('FILE', 'DIR')),
    resource_id BIGINT NOT NULL,
    owner_user_id BIGINT NOT NULL,
    shared_with_user_id BIGINT NOT NULL,
    permissions VARCHAR(50) DEFAULT 'VIEW' NOT NULL CHECK (permissions IN ('VIEW', 'EDIT', 'OWNER')),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT shares_owner_user_id FOREIGN KEY (owner_user_id) REFERENCES users(id),
    CONSTRAINT shares_shared_with_user_id FOREIGN KEY (shared_with_user_id) REFERENCES users(id),
    UNIQUE (resource_type, resource_id, shared_with_user_id)
);

CREATE OR REPLACE FUNCTION init_user_folder_func()
RETURNS TRIGGER AS $$
    DECLARE
        root_dir_id BIGINT;
    BEGIN
        INSERT INTO dirs (name, parent_id)
        VALUES (NEW.id || '_' || NEW.email, NULL)
        RETURNING id INTO root_dir_id;
        INSERT INTO user_dirs (user_id, dir_id, role)
        VALUES (NEW.id, root_dir_id, 'OWNER');
        RETURN NEW;
    END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE TRIGGER init_user_folder
    AFTER INSERT ON users
    FOR EACH ROW
    EXECUTE FUNCTION init_user_folder_func();